In [1]:
import numpy as np
import pandas as pd

In [2]:
data_path = "E:\master\\final_project\data\my_data\embedding_output_data\deephage_original_data\\100_400\\fold_1\\train\\labels.npy"
a = np.load(data_path)
print(a.shape)

(80000,)

In [3]:
df = pd.DataFrame({
    "sequence": vectors,
    "target": labels
})
df.head()

                                            sequence  target
0  ATGTAGGGGCATTTTTTATATTTAAATAACTAGAGTAATTAACGTA...       0
1  CTTCTCTAAATTTATCGTTAGCTTTCCACCTTGATATAGTAGCGCG...       0
2  AAGCTAACGATAAATTTAGAGAAGGGTTTAAAGGATATCAAGCTGA...       0
3  GCCACGTCCGCCCTTTGCAATGATGTTAAGTATTCCTTTATCTTTA...       0
4  TACTTAACATCATTGCAAAGGGCGGACGTGGCTCAGGTAAGTCGTC...       0

In [4]:
from common.env_config import config

for i in range(5):
    fold = i + 1
    for j in range(4):
        if j == 0:
            min_size = 100
            max_size = 400
            overlap = 30
            max_length_tokenizer = int(max_size * 0.25)
        elif j == 1:
            min_size = 400
            max_size = 800
            overlap = 30
            max_length_tokenizer = int(max_size * 0.25)
        elif j == 2:
            min_size = 800
            max_size = 1200
            overlap = 50
            max_length_tokenizer = 512
        elif j == 3:
            min_size = 1200
            max_size = 1800
            overlap = 70
            max_length_tokenizer = 512
        else:
            raise ValueError

        # if j < 2:
        #     continue

        group = f"{min_size}_{max_size}"
        print(f"group: {group}, fold: {fold}")

        train_vector_file = f"{config.CONTIG_OUTPUT_DATA_DIR}/{group}/fold_{fold}/train/fcgr_vectors.npy"
        train_label_file = f"{config.CONTIG_OUTPUT_DATA_DIR}/{group}/fold_{fold}/train/fcgr_labels.npy"
        test_vector_file = f"{config.CONTIG_OUTPUT_DATA_DIR}/{group}/fold_{fold}/test/fcgr_vectors.npy"
        test_label_file = f"{config.CONTIG_OUTPUT_DATA_DIR}/{group}/fold_{fold}/test/fcgr_labels.npy"

        train_vectors = np.load(train_vector_file, allow_pickle=True)
        train_labels = np.load(train_label_file)
        test_vectors = np.load(test_vector_file, allow_pickle=True)
        test_labels = np.load(test_label_file)

        train_df = pd.DataFrame({
            "sequence": train_vectors,
            "target": train_labels
        })
        test_df = pd.DataFrame({
            "sequence": test_vectors,
            "target": test_labels
        })
        train_df.to_csv(f"{config.CONTIG_OUTPUT_DATA_DIR}/{group}/fold_{fold}/train/data.csv", index=False)
        test_df.to_csv(f"{config.CONTIG_OUTPUT_DATA_DIR}/{group}/fold_{fold}/test/data.csv", index=False)

group: 100_400, fold: 1
group: 400_800, fold: 1
group: 800_1200, fold: 1
group: 1200_1800, fold: 1
group: 100_400, fold: 2
group: 400_800, fold: 2
group: 800_1200, fold: 2
group: 1200_1800, fold: 2
group: 100_400, fold: 3
group: 400_800, fold: 3
group: 800_1200, fold: 3
group: 1200_1800, fold: 3
group: 100_400, fold: 4
group: 400_800, fold: 4
group: 800_1200, fold: 4
group: 1200_1800, fold: 4
group: 100_400, fold: 5
group: 400_800, fold: 5
group: 800_1200, fold: 5
group: 1200_1800, fold: 5

,Phage_ID,Length,GC_content,Taxonomy,Completeness,Host,Lifestyle,Cluster,Subcluster,Phage_source
0,J02448.1,6407,40.939597,Inoviridae,High-quality,Escherichia coli,virulent,cluster_269726,subcluster_338485,Genbank
1,M14428.1,5386,44.337170,NaN,Medium-quality,Escherichia coli C,virulent,cluster_24186,subcluster_30301,Genbank
2,AF059243.1,4248,50.823917,Riboviria,High-quality,Enterobacteriaceae,virulent,cluster_39628,subcluster_49796,Genbank
3,AF227250.1,3486,46.528973,Riboviria,High-quality,Escherichia coli,virulent,cluster_68527,subcluster_86649,Genbank
4,NC_001330.1,6087,45.178249,Microviridae,High-quality,Escherichia coli,virulent,cluster_158413,subcluster_199459,RefSeq

In [5]:
df.Phage_source.unique()

array(['Genbank', 'RefSeq', 'DDBJ', 'EMBL', 'PhagesDB', 'GPD', 'GVD',
       'MGV', 'TemPhD'], dtype=object)